project_name: fs

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: fs
    ldflags:
      - -s -w
      - -X github.com/kis9a/fs/cmd.Version={{.Version}}
      - -X github.com/kis9a/fs/cmd.BuildSHA={{.ShortCommit}}
      - -X github.com/kis9a/fs/cmd.BuildTag={{.Tag}}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
